### PR TITLE
autoload: specify full package name and path

### PR DESCRIPTION
**Pull request by jayaddison**
These changes aren't tested for `Dop`, but since checking in on https://github.com/morris/lessql/pull/56 and spotted #3, I figured it could be worth applying the same change here too.

### CODE REVIEW

**Comment by morris** [comment]
hi, thanks for opening the PR! would it be possible to keep both psr-0 and psr-4? and shouldn't it be `"Dop\\": "src/Dop"` if the files are not moved?

**Comment by jayaddison** [comment]
@morris No problem, and yes, oops - you're totally correct regarding the lack of file move.  Do you have a preference / know if there's a recommended standard there?  (while we investigate/determine that, I can apply the same changes as made in `lessql`)

**Comment by jayaddison** [comment]
@morris Doing a little more research, I do find a few examples where both psr-0 and psr-4 are present, so it seems a good idea to keep both in place.

Let's see whether we can find a popular composer-based PHP project where that's the case, and perhaps follow their practice?

(dup comment; posted in the other pull request by accident)

**Comment by jayaddison** [comment]
(reassuringly, the [spec](https://www.php-fig.org/psr/psr-4/) also mentions that it is interoperable and can be used in conjunction with existing autoloaders)

**Comment by jayaddison** [comment]
Ref: https://www.drupal.org/project/drupal/issues/1971198

**Comment by jayaddison** [comment]
Also ref: Joomla have opted not to migrate two of their repository branches due to backwards incompatibilities; they offer some notes under the 'File Structure' section here: https://framework.joomla.org/contribute

**Comment by jayaddison** [comment]
@morris From the Joomla reference above, there do seem to be legitimate reasons not to upgrade to PSR-4 in some cases, and as the project maintainer here and for `lessql` I'll leave that for you to determine (I certainly don't want to cause any breakages).

That said, it does seem worth trying to fix the initial issue from https://github.com/morris/lessql/pull/55 in terms of avoiding accidental naming lookups via the global autoload namespace.

I've updated the pull request to provide a PSR-0 full path - that might be the best middle-ground if PSR-4 isn't possible.  Unfortunately I don't have a full development environment set up at the moment so I haven't yet tested this.

Edit: clarify some wording

**Comment by morris** [comment]
since PSR-0 is deprecated, i think it's fine to go forward with PSR-4 - thanks for the research! i'd rather not change the directory structure (neither lessql nor dop have deep directory trees anyways). so just change to standard psr-4 and i will happily test & merge (lessql too) :)

**Comment by jayaddison** [comment]
@morris Great :)  I've applied what I think should be the changes in each PR now; let me know if that seems to work or whether I should spend a bit of time soon to set up a PHP environment again.

**Comment by morris** [comment]
Thanks! I will release soon while also listing you as a contributor if that's alright for you.

**Comment by jayaddison** [comment]
All sounds good to me, thanks @morris !

**Pull request merged**
